name: "build feature branch"
on:  [ push ]
jobs:
  "Build_Docker_Container":
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build container
        run: docker buildx build -t react-open-arch .